# Generated by Django 5.2.6 on 2025-11-28 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_producto_condicion_producto_imagen_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='ganador',
        ),
    ]
