# Generated by Django 5.2.6 on 2025-11-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auction_ganador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start_time',
        ),
    ]
