# Generated by Django 5.2.6 on 2025-11-28 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_remove_auction_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
